import type { Metadata } from "next";
import localFont from "next/font/local";
import { appConfig } from "@/config/appConfig";
import Header from "@/components/layout/Header";
import "./globals.css";
import Footer from "@/components/common/Footer";


const danaRegular = localFont({
  src: "./fonts/Dana-Regular.woff"
})

export const metadata: Metadata = {
  title: `${appConfig.appName}`,
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{  children: React.ReactNode;}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={`${danaRegular.className} antialiased`}>
        <Header/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
