// types
import type { Metadata } from "next";

// config
import { appConfig } from "@/config/appConfig";

// layout components
import Header from "@/components/layout/Header";
import Footer from "@/components/common/Footer/Footer";


// import Swiper and modules styles
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

import "./globals.css";

// fonts
import localFont from "next/font/local";

const danaRegular = localFont({
  src: "./fonts/Dana-Regular.woff"
})

// title
export const metadata: Metadata = {
  title: `${appConfig.appName}`,
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{  children: React.ReactNode;}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={`${danaRegular.className} antialiased`}>
        <Header/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
